### ISSUE TITLE
ImportError: cannot import name post_migrate

### ISSUE THREAD

**Issue by xiaotuanyu120** [the5fire/django-admin-sample#1]
**按照提示操作，当执行<code>python manage.py runserver 0.0.0.0:9000</code>时，提示如下错误**

``` bash
python manage.py runserver 0.0.0.0:9000
Validating models...

Unhandled exception in thread started by <function wrapper at 0x7fd3a0c6c050>
Traceback (most recent call last):
  File "/tmp/django_admin_demo/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 93, in wrapper
    fn(*args, **kwargs)
  File "/tmp/django_admin_demo/venv/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 101, in inner_run
    self.validate(display_num_errors=True)
  File "/tmp/django_admin_demo/venv/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/tmp/django_admin_demo/venv/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/tmp/django_admin_demo/venv/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/tmp/django_admin_demo/venv/lib/python2.7/site-packages/django/db/models/loading.py", line 78, in _populate
    self.load_app(app_name)
  File "/tmp/django_admin_demo/venv/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/tmp/django_admin_demo/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/tmp/django_admin_demo/venv/lib/python2.7/site-packages/xadmin/models.py", line 13, in <module>
    from django.db.models.signals import post_migrate
ImportError: cannot import name post_migrate
```

**pip安装环境为**

``` bash
pip freeze
Django==1.6.5
django-crispy-forms==1.6.0
django-formtools==1.0
httplib2==0.9.2
xadmin==0.6.1
```

**python版本为**

``` bash
python -V
Python 2.7.11
```

**系统环境**

``` bash
cat /etc/centos-release
CentOS release 6.8 (Final)

uname -a
Linux zack 2.6.32-642.el6.x86_64 #1 SMP Tue May 10 17:27:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by the5fire** [comment]
xadmin版本有点高了。你试试用Django1.7，不行的话，就用xadmin0.5
